# Generated by Django 3.1.4 on 2021-01-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_data',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop', models.CharField(max_length=500)),
                ('api_key', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
