# Generated by Django 3.1.4 on 2021-01-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencerapp', '0002_auto_20210108_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_data',
            old_name='id',
            new_name='shop_id',
        ),
    ]
